### ISSUE TITLE
CapabilityProfile.load() fails on ios

### ISSUE THREAD

**Issue by ayushin** [andrey-ushakov/esc_pos_utils#19]
```
flutter: >>> Unsupported operation: Isolate.resolvePackageUri, #0      Isolate.resolvePackageUri (dart:isolate-patch/isolate_patch.dart:340:7)
#1      resolveUri (package:resource/src/resolve.dart:11:20)
#2      Resource.readAsString (package:resource/src/resource.dart:74:21)
#3      CapabilityProfile.load (package:esc_pos_utils/src/capability_profile.dart:26:33)
#4      PrinterBloc._selectPrinter (package:aahi_sell/bloc/printer_bloc.dart:108:50)
#5      _rootRunUnary (dart:async/zone.dart:1198:47)
#6      _CustomZone.runUnary (dart:async/zone.dart:1100:19)
#7      _FutureListener.handleValue (dart:async/future_impl.dart:143:18)
#8      Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:696:45)
#9      Future._propagateToListeners (dart:async/future_impl.dart:725:32)
#10     Future._addListener.<anonymous closure> (dart:async/future_impl.dart:393:9)
#11     _rootRun (dart:async/zone.dart:1190:13)
#12     _CustomZone.run (dart:async/zone.dart:1093:19)
#13     _CustomZone.runGuarded (dart:async/zone.dart:997:7)
#14     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:1037:23)
#15     _microtaskLoop (dart:async/schedule_microtask.dart:41:21)
#16     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50:5)

```

**Comment by yarmat** [comment]
on androids too

**Comment by andrey-ushakov** [comment]
Thank you, it should be fixed now.

**Comment by Lyba97** [comment]
@andrey-ushakov I am facing the same issue. Can anyone tell me what to do with this issue? 

[ERROR:flutter/lib/ui/ui_dart_state.cc(199)] Unhandled Exception: Null check operator used on a null value
E/flutter (23782): #0      PlatformAssetBundle.load (package:flutter/src/services/asset_bundle.dart:222:39)
E/flutter (23782): #1      AssetBundle.loadString (package:flutter/src/services/asset_bundle.dart:68:33)
E/flutter (23782): #2      CachingAssetBundle.loadString.<anonymous closure> (package:flutter/src/services/asset_bundle.dart:165:56)
E/flutter (23782): #3      _LinkedHashMapMixin.putIfAbsent (dart:collection-patch/compact_hash.dart:311:23)
E/flutter (23782): #4      CachingAssetBundle.loadString (package:flutter/src/services/asset_bundle.dart:165:27)
E/flutter (23782): #5      CapabilityProfile.load (package:esc_pos_utils/src/capability_profile.dart:25:10)
E/flutter (23782): #6      main (package:flutter_app_printer/main.dart:9:43)
E/flutter (23782): #7      _runMainZoned.<anonymous closure>.<anonymous closure> (dart:ui/hooks.dart:142:25)
E/flutter (23782): #8      _rootRun (dart:async/zone.dart:1354:13)
E/flutter (23782): #9      _CustomZone.run (dart:async/zone.dart:1258:19)
E/flutter (23782): #10     _runZoned (dart:async/zone.dart:1789:10)
E/flutter (23782): #11     runZonedGuarded (dart:async/zone.dart:1777:12)
E/flutter (23782): #12     _runMainZoned.<anonymous closure> (dart:ui/hooks.dart:138:5)
E/flutter (23782): #13     _delayEntrypointInvocation.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:283:19)
E/flutter (23782): #14     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:184:12)

**Comment by dayronpf** [comment]
**I/flutter (12056): Something really unknown: Null check operator used on a null value**

When I go to load final profile = await CapabilityProfile.load();
It never finds the **capabilities.json** file
If you could help me with this problem I would appreciate it, I have tried to add it as assets in the project but it does not work.
Thanks
