### ISSUE TITLE
Localization

### ISSUE THREAD

**Issue by niktses** [andrey-ushakov/esc_pos_utils#2]
We need to be able to create PosCodeTable.
It seems to me that not all printers have the same code tables.
I need to use greek on epson printer.
Check here for epson code pages.
https://reference.epson-biz.com/modules/ref_charcode_en/index.php?content_id=1

I would like to be able to do something like PosCodeTable(15).

**Comment by niktses** [comment]
it seems to me that even if i alter your code to pass 15 for greek it is still not printing for invalid character

**Comment by andrey-ushakov** [comment]
Hi,

Have you tried to encode your text before sending it to the printer using `charset_converter` package?
Here are some examples:
https://github.com/andrey-ushakov/esc_pos_printer#using-code-tables

You are right, different printers may support different code tables and/or have different codes for them. It's better to check your printer's specifications (usually you can print a ticket listing all the supporter code tables).

**Comment by niktses** [comment]
thanks i saw after your comment that you have a new version
