### ISSUE TITLE
Text not printing in some pinters

### ISSUE THREAD

**Issue by mjafartp** [andrey-ushakov/esc_pos_utils#23]
in some printers texts not printing...

only printing image.
here is the printer self test print page.
![printer](https://user-images.githubusercontent.com/5754379/90600552-67fbcd00-e214-11ea-950a-d166d427fe05.jpeg)

Showing default code page 255 and encoding UTF8

Printer Name :  E-POS
Model :  ECO250

**Comment by jonathantribouharet** [comment]
Here what I have with an EPSON TM-T20iii
![test](https://user-images.githubusercontent.com/188946/95603380-7b7a2600-0a56-11eb-842a-39ee6581f554.jpg)

**Comment by DhavalRKansara** [comment]
@mjafartp I am also facing the same issue text is not printing with my label printer how would you fix it?
