### ISSUE TITLE
Depends on esc_pos_utils ^0.3.6

### ISSUE THREAD

**Issue by ImTung** [andrey-ushakov/esc_pos_utils#24]
Hello!
I got errors when install `esc_pos_`.

Here my packages:
```
esc_pos_utils: ^0.4.7
esc_pos_bluetooth: ^0.2.8
esc_pos_printer: ^3.2.7
flutter_bluetooth_basic: ^0.1.5
```

When I get package ```flutter pub get``` I got:
```
Because esc_pos_bluetooth >=0.2.8 depends on esc_pos_utils ^0.3.6 and ineonspm depends on esc_pos_utils ^0.4.7, esc_pos_bluetooth >=0.2.8 is forbidden.
So, because ineonspm depends on esc_pos_bluetooth ^0.2.8, version solving failed.
```

**Comment by MasIzzudin** [comment]
is there a solution for this?

**Comment by ImTung** [comment]
> is there a solution for this?

folk and handle in local

**Comment by excode** [comment]
Hi @ImTung  Please explain "folk and handle in local"

Thank you

**Comment by ImTung** [comment]
> Hi @ImTung Please explain "folk and handle in local"
> 
> Thank you

fork this repo, change pubspec with local path

**Comment by wwandreww** [comment]
The package was updated to be compatible with Null-Safety. The libraries were updated too.
I'm closing this issue but feel free to reopen it if need.
I don't currently have a POS printer to test and support this plugin so your PRs are welcome!
