### ISSUE TITLE
Maintenance for this package

### ISSUE THREAD

**Issue by DhavalRKansara** [andrey-ushakov/esc_pos_utils#38]
@andrey-ushakov Are you working on this package or not? There are 20+ issues that are open and you are not adding any comments on them. Also As I can the last release for this package was made on Mar 12, 2020. Can you please provide an update on it or add some contributors under this package?

**Comment by wwandreww** [comment]
The package was updated to be compatible with Null-Safety. The libraries were updated too.
I'm closing this issue but feel free to reopen it if need.
I don't currently have a POS printer to test and support this plugin so your PRs are welcome!
