### ISSUE TITLE
Rows with PosTextSize> size 1

### ISSUE THREAD

**Issue by niktses** [andrey-ushakov/esc_pos_utils#4]
ticket.row([
      PosColumn(
        text: "Licence Plate",
        width: 6,
        styles: PosStyles(align: PosAlign.right, width: PosTextSize.size2, height: PosTextSize.size2),
      ),
      PosColumn(
        text: 'AAA1111',
        width: 6,
        styles: PosStyles(align: PosAlign.left, width: PosTextSize.size2, height: PosTextSize.size2),
      ),
    ]);

column width is not correctly calculated if size is not PosTextSize.size1

**Comment by andrey-ushakov** [comment]
Thank you!
Fixed.
