### ISSUE TITLE
Flutter V2.0

### ISSUE THREAD

**Issue by alaindixon** [andrey-ushakov/esc_pos_utils#40]
Hi,

The image package is use by firebase, they are using the version 3.x.x   
Obviously you are using the previous version 2.x.x, have you planned to migrate your package to image 3.x.x?

Maybe integrate the brand new you NullSafe?

Thanks

**Comment by niktses** [comment]
+1 plz migrate to null safety

**Comment by pmaAdvensyn** [comment]
i can't use dart.html without this migration

**Comment by jobypthomas** [comment]
+1

**Comment by wwandreww** [comment]
The package was updated to be compatible with Null-Safety. The libraries were updated too.
I'm closing this issue but feel free to reopen it if need.
I don't currently have a POS printer to test and support this plugin so your PRs are welcome!
