### ISSUE TITLE
Slow printing text

### ISSUE THREAD

**Issue by niktses** [andrey-ushakov/esc_pos_utils#5]
Resetting the image after every added text slows printing but changing the styling every time does not.
Removed reset() from here:
  void textEncoded(
    Uint8List textBytes, {
    PosStyles styles = const PosStyles(),
    int linesAfter = 0,
  }) {
    _text(textBytes, styles: styles);
    // Ensure at least one line break after the text
    emptyLines(linesAfter + 1);
    reset();
  }

and changed this:
 bytes += styles.bold ? cBoldOn.codeUnits : <int>[];
    bytes += styles.turn90 ? cTurn90On.codeUnits : <int>[];
    bytes += styles.reverse ? cReverseOn.codeUnits : <int>[];
    bytes += styles.underline ? cUnderline1dot.codeUnits : <int>[];
    bytes += styles.fontType == PosFontType.fontB ? cFontB.codeUnits : <int>[];
    // Characters size
    if (styles.height.value != PosTextSize.size1.value ||
        styles.width.value != PosTextSize.size1.value) {
      bytes += Uint8List.fromList(
        List.from(cSizeGSn.codeUnits)
          ..add(PosTextSize.decSize(styles.height, styles.width)),
      );
    }

to this:
bytes += styles.bold ? cBoldOn.codeUnits : cBoldOff.codeUnits;
    bytes += styles.turn90 ? cTurn90On.codeUnits : cTurn90Off.codeUnits;
    bytes += styles.reverse ? cReverseOn.codeUnits : cReverseOff.codeUnits;
    bytes += styles.underline ? cUnderline1dot.codeUnits : cUnderlineOff.codeUnits;
    bytes += styles.fontType == PosFontType.fontB ? cFontB.codeUnits : cFontA.codeUnits;
    // Characters size
    bytes += Uint8List.fromList(
      List.from(cSizeGSn.codeUnits)
        ..add(PosTextSize.decSize(styles.height, styles.width)),
    );

and performance improvements were huge.
Consider testing this and if it works for you too consider changing it.

**Comment by andrey-ushakov** [comment]
Thank you for this!
It seems that it may explain [this issue](https://github.com/andrey-ushakov/esc_pos_printer/issues/39)!

Actually, with my [Xprinter XP-N160I](http://www.xprinter.net/index.php/Product/product_detail/id/4/cid2/21/cid/1) I have no performance issues, that's why I haven't noticed this.
I will try to test soon and improve the library!

BTW, I'm not sure if you have mentioned it somewhere already, but what's your printer brand and model, please?

**Comment by niktses** [comment]
I'm using an Epson TM-T20ii-003. I also use a rongta rpp300 for its bluetooth but this one is pretty much garbage. Actually if you are interested the rongst has an issue that for some unknown to me reason exposes 2 bluetooth signals one of which does absolutely nothing and unfortunately this is the one your bluetooth library catches. The other one requires password so it probably affects it somehow. I fix this by bonding it beforehand and using this library as well "flutter_bluetooth_serial" to get the already bonded devices. The epson works fine. I have only tested in android so far.

**Comment by andrey-ushakov** [comment]
> Resetting the image after every added text slows printing but changing the styling every time does not.

Unfortunately, changing the styling every time creates this issue (for some printers only): https://github.com/andrey-ushakov/esc_pos_bluetooth/issues/1

However, it seems I've found a way how to avoid this. Could you please test the performance issue using your Epson TM-T20ii-003 and the latest library?

Here there is a good test: https://github.com/andrey-ushakov/esc_pos_printer/issues/39#issuecomment-583995790

Thanks!

**Comment by niktses** [comment]
In my case it works fine now.

**Comment by andrey-ushakov** [comment]
Ok! I'm closing this issue

**Comment by Fethi-Hamdani** [comment]
I'm having the same performance issue with an SPRT L31 printer, any help
