### ISSUE TITLE
Package gbk_codec Needs to be updated

### ISSUE THREAD

**Issue by tehsunnliu** [andrey-ushakov/esc_pos_utils#56]
gbk_codec 0.4.0 is now available.
Some packages give html dependency version incompatible exception.

**Comment by wwandreww** [comment]
The package was updated to be compatible with Null-Safety. The libraries were updated too.
I'm closing this issue but feel free to reopen it if need.
I don't currently have a POS printer to test and support this plugin so your PRs are welcome!
