### ISSUE TITLE
Image Raster bug

### ISSUE THREAD

**Issue by niktses** [andrey-ushakov/esc_pos_utils#7]
you need to add this check because if image is already divisible by 8 you add 8 extra pixels and image is distorted.

if(widthPx % 8 != 0) {
      final targetWidth = (widthPx + 8) - (widthPx % 8);
      final missingPx = targetWidth - widthPx;
      final extra = Uint8List(missingPx);
      for (int i = 0; i < heightPx; i++) {
        final pos = (i * widthPx + widthPx) + i * missingPx;
        oneChannelBytes.insertAll(pos, extra);
      }
    }

**Comment by andrey-ushakov** [comment]
Fixed
